name: Build and Release

on:
  push:
    branches:
      - experimental
jobs:
  build-wheel:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      matrix:
        buildplat:
          - [ubuntu-latest, manylinux_x86_64]
          # - [macos-14, macosx_arm64]
          # - [macos-13, macosx_x86_64]
        python:
          - ["cp310", "3.10"]
          - ["cp311", "3.11"]
          - ["cp312", "3.12"]
    runs-on: ${{ matrix.buildplat[0] }}
    if: github.ref == 'refs/heads/experimental'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2.0.1
        with:
          environment-name: pyensmallen
          create-args: armadillo ensmallen
          init-shell: bash
          generate-run-shell: true

      - name: Install openblas
        run: |
          sudo apt-get install libopenblas-dev

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.0
        env:
          CIBW_BEFORE_BUILD: |
            export PKG_CONFIG_PATH="/Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig:$PKG_CONFIG_PATH"
            export CMAKE_PREFIX_PATH="/Users/runner/micromamba/envs/pyensmallen"
            ls -la /Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig || echo "pkgconfig dir not found"
            python -m pip install -v build
            python -c "import os; print('Environment:', os.environ)"
          CIBW_ENVIRONMENT_LINUX: >-
            MAMBA_ROOT_PREFIX="/host/home/runner/micromamba"
            CMAKE_PREFIX_PATH="/host/home/runner/micromamba/envs/pyensmallen"
            VERBOSE=1
          CIBW_ENVIRONMENT_MACOS: >-
            PKG_CONFIG_PATH="/Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig"
            CMAKE_PREFIX_PATH="/Users/runner/micromamba/envs/pyensmallen"
            VERBOSE=1
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          CIBW_BUILD_VERBOSITY: 3
        continue-on-error: true # Let it complete even if there's an error


      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-logs
          path: |
            ~/.local/share/cibuildwheel/**/*.log
            /tmp/cibw*/**/*.log
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          path: wheelhouse/*.whl
